apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-con
        image: 521607973210.dkr.ecr.ap-northeast-2.amazonaws.com/web-argo:2
